### ISSUE TITLE
"Uups, I don't know you! Maybe try to login again. See console for more information!" prompt

### ISSUE THREAD

**Issue by beatenpatharchives** [caliog/Rolecraft#6]
When I try to use commands following the prompts on the wiki, it gives me "Uups, I don't know you! Maybe try to login again. See console for more information!"

I am the server owner, and do not think the reason is that I do not have the permissions because of that. I think it is something else I have not done yet. 

Help Please

**Comment by caliog** [comment]
Is this still happening? Sometimes this issue just pops up and never appears again. I still don't know why it happens.

**Comment by Mrs-Feathers** [comment]
i had it happen because i messed something up when i was compiling the .jar.. maybe your browser didn't download the rolecraft.jar correctly? that's very possible. see if it works again by redownloading the plugin. i've never had it happen before or since the time i made it happen by my mistake with the .jar so beyond that, all i can say for help is "make sure your bukkit server is updated"

**Comment by caliog** [comment]
Let me move this to bukkit: https://dev.bukkit.org/projects/rolecraft/issues/345
